resolver 127.0.0.11 valid=10s;

server {
    listen 443 ssl;
    server_name registry.localhost;
    client_max_body_size 0;

    ssl_certificate     /etc/nginx/certs/registry.localhost.pem;
    ssl_certificate_key /etc/nginx/certs/registry.localhost-key.pem;

    # --- Token endpoint ---
    location = /v2/token {
        auth_basic "Registry";
        auth_basic_user_file /etc/nginx/certs/htpasswd;
        set $user $remote_user;
        proxy_pass http://keypebble:8080/v2/token$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Authenticated-User $user;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Docker Registry API ---
    location /v2/ {
        proxy_pass http://registry:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
